### ISSUE TITLE
pdf missing plots

### ISSUE THREAD

**Issue by sabaferdous12** [LearnToDiscover/sandpaper#8] opened 2022-06-29 16:38 UTC
Pdf doesn't show the plots/graphs and the reason is that Pandoc is ignoring html <img> tag, 

So the potential solution is to add another function that will replace that line with image insertion line. 

This 
img src="fig/02-data_frames_2-rendered-unnamed-chunk-3-1.png" width="2016" style="display: block; margin: auto;" />
To
![](fig/02-data_frames_2-rendered-unnamed-chunk-3-1.png)

Thanks for the solution @dpshelio :)

**Comment by milanmlft** [comment] 2023-05-26 15:27
@sabaferdous12 is this the same as #20?

**Comment by milanmlft** [comment] 2023-05-26 15:46
Closing as this is a duplicate of #20

**Closed as completed by milanmlft** 2023-05-26 15:46 UTC
